---
- name: Tasks for slave
  block:
  - name: Stop PostgreSQL server
    systemd:
      name: postgresql-12
      state: stopped

  - name: Ensure data-backup directory does not exist
    file:
      path: /var/lib/pgsql/12/data-backup
      state: absent

  - name: Move data backup
    shell: mv data data-backup
    args:
      chdir: /var/lib/pgsql/12/

  - name: Create data directory
    file:
      path: /var/lib/pgsql/12/data
      mode: 0700
      owner: postgres
      group: postgres
      state: directory

  - name: Backup initial data from master
    shell: su - postgres -c "PGPASSWORD={{ replica_password }} pg_basebackup -w -h {{ hostvars['pgmaster01'].replication_ip_address }} -U replica -D /var/lib/pgsql/12/data -Fp -P -R -X stream"

  - name: Update /var/lib/pgsql/12/data/postgresql.conf
    lineinfile:
      path: /var/lib/pgsql/12/data/postgresql.conf
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
    - { regexp: "#listen_addresses = 'localhost'", line: "listen_addresses = '{{ public_ip_address }},{{ replication_ip_address }}'" }
    - { regexp: "#hot_standby = off", line: "hot_standby = on" }
    - { regexp: "#promote_trigger_file = ''", line: "promote_trigger_file = '/tmp/postgresql.trigger.5432'" }

  - name: Create files for recovery
    file:
      path: /var/lib/pgsql/12/data/{{ item }}
      mode: 0600
      owner: postgres
      group: postgres
      state: touch
    with_items:
      - "standby.signal"
      - "recovery.signal"

  - name: Start PostgreSQL server
    systemd:
      name: postgresql-12
      state: started
  
  when: "'pgslave' in group_names"
