---
- name: Tasks for master
  block:
  - name: Change postgres password
    shell: sudo -u postgres psql -c "ALTER USER postgres WITH password '{{ db_password }}'"

  - name: Update /var/lib/pgsql/12/data/postgresql.conf
    lineinfile:
      path: /var/lib/pgsql/12/data/postgresql.conf
      backup: true
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      backrefs: true
    with_items:
    - { regexp: "#listen_addresses = 'localhost'", line: "listen_addresses = '{{ public_ip_address }},{{ replication_ip_address }}'" }
    - { regexp: '#wal_level = minimal', line: 'wal_level = hot_standby' }
    - { regexp: '#synchronous_commit = on', line: 'synchronous_commit = local' }
    - { regexp: '#archive_mode = off', line: 'archive_mode = on' }
    - { regexp: "#archive_command = ''", line: "archive_command = 'cp %p /var/lib/pgsql/12/archive/%f'" }
    - { regexp: '#max_wal_senders = 0', line: 'max_wal_senders = 2' }
    - { regexp: '#wal_keep_segments = 0', line: 'wal_keep_segments = 2' }
    - { regexp: "#synchronous_standby_names = ''", line: "synchronous_standby_names = 'pgslave01'" }

  - name: Create archive directory
    file:
      path: /var/lib/pgsql/12/archive
      mode: 0700
      owner: postgres
      group: postgres
      state: directory

  - name: Update pg_hba.conf
    blockinfile:
      path: /var/lib/pgsql/12/data/pg_hba.conf
      backup: true
      insertafter: '#host replication postgres ::1/128 ident'
      block: |
        # Localhost
        host replication replica 127.0.0.1/32 md5
        # PostgreSQL Master IP address
        host replication replica {{ replication_ip_address }}/32 md5
        # PostgreSQL Slave IP address
        host replication replica {{ hostvars['pgslave01'].replication_ip_address }}/32 md5
      
  - name: Restart PostgreSQL server
    systemd:
      name: postgresql-12
      enabled: yes
      state: restarted

  - name: Check if replication user exists
    shell: sudo -u postgres psql -c "\du" | grep '^ replica' | wc -l
    register: replicauser

  - name: Create replication user
    shell: sudo -u postgres psql -c "CREATE USER replica REPLICATION LOGIN ENCRYPTED PASSWORD '{{ replica_password }}'"
    when: replicauser.stdout == "0"
  
  when: "'pgmaster' in group_names"